
debug: false

server:
  port: 8091

spring:
  profiles:
    active: dev
  application:
    name: family
  main:
    allow-bean-definition-overriding: true #当遇到相同的名字，是否允许覆盖
  data:
    mongodb:
      host: localhost
      port: 27000
      database: family
      username: zeal
      password: zealsay
      authentication-database: admin

beetl:
  suffix: html

app:
  username: admin
  password: 123456
  default-password: 123


---
spring:
  profiles: prod
  application:
    name: family
  main:
    allow-bean-definition-overriding: true #当遇到相同的名字，是否允许覆盖
  data:
    mongodb:
      host: ${MONGO_HOST}  #改成你的mongo的host
      port: ${MONGO_PORT}  #改成你的mongo的port
      database: ${DATABASE}  #改成你的应用在mongo中的存储空间
      username: ${USERNAME}  #改成你的mongo的登录用户名
      password: ${PASSWORD}  #改成你的mongo的登录密码
      authentication-database: ${AUTH_DATABASE}  #改成你的mongo的授权数据库

beetl:
  suffix: html

app:
  username: ${ADMIN_USERNAME}  #配置后台管理员默认账号
  password: ${ADMIN_PASSWORD}  #配置后台管理员默认密码
  default-password: ${USER_PASSWORD}  #配置后台添加新成员时，新成员登录的默认密码